name: إنشاء أرشيف للكود
on: [push]
jobs:
  build-archive:
    runs-on: ubuntu-latest
    steps:
      - name: تحميل الكود
        uses: actions/checkout@v3
      - name: إنشاء أرشيف (Zip)
        run: zip -r project_source.zip . -x "node_modules/*" ".git/*"
      - name: رفع الأرشيف كمنتج (Artifact)
        uses: actions/upload-artifact@v3
        with:
          name: project-source
          path: project_source.zip
